"""Tests for the AI client: what refuses, in what order, and what a refusal is allowed to touch.

The transport is a stand-in that records every call, which is what makes the ordering claims
checkable: a policy refusal that still sent a request would look identical in the return value and
differ only here.
"""
import datetime as dt
import json
from pathlib import Path
import tempfile
import unittest

from local_observe.ai import budget as budget_module, telemetry as telemetry_module
from local_observe.ai import client
from local_observe.ai.client import AiClient, AiError, AiNotConfigured
from local_observe.http import TransportError
from local_observe.log import JsonLinesFormatter

NOW = dt.datetime(2026, 9, 8, 10, 30, tzinfo=dt.timezone.utc)
WINDOW = {'start': '2026-09-08T10:00:00+00:00', 'end': '2026-09-08T10:05:00+00:00'}
MEASURED = {'schema_version': 1, 'context_tokens': 8192, 'tools': False, 'json_mode': True,
            'streaming': True, 'vision': False, 'parallel': 2, 'quant': 'Q4_K_M',
            'measured_tok_per_s': 12.5}
UNMEASURED = dict(MEASURED, context_tokens='unknown', json_mode='unknown')
PUBLIC_REMOTE = {'generate': True, 'remote': True, 'redact': ['secret_keys', 'no_free_text'],
                 'label': 'generated by a remote model'}
LOCAL_ONLY = {'generate': True, 'remote': False, 'redact': ['secret_keys'], 'label': ''}
REFUSED = {'generate': False, 'remote': False, 'redact': [], 'label': ''}
POLICY = {'schema_version': 1, 'classes': {'public': PUBLIC_REMOTE, 'internal': LOCAL_ONLY,
                                           'restricted': REFUSED}}
CANARY = 'sentry-secret-do-not-send'
REPLY = {'model': 'qwen3-30b', 'choices': [{'message': {'content': 'the volume filled'},
                                           'finish_reason': 'stop'}],
         'usage': {'prompt_tokens': 44, 'completion_tokens': 48}}


class FakeTransport:
    """Counts requests and answers with *reply*; every refusal test asserts the count is zero."""

    def __init__(self, reply=None, status=200, error=None):
        self.reply = REPLY if reply is None else reply
        self.status = status
        self.error = error
        self.calls = []

    def request(self, method, path='', payload=None, headers=None):
        self.calls.append({'method': method, 'path': path, 'payload': payload})
        if self.error is not None:
            raise self.error
        return self.status, self.reply


def reference(**changes):
    item = {'source': 'sigma-example', 'query_type': 'sigma-count',
            'parameters': {'rule_id': 'disk-full'}, 'window': dict(WINDOW), 'schema_version': 1,
            'expires_at': '2026-09-08T11:00:00+00:00'}
    item.update(changes)
    return item


def build(*, capability=None, policy=None, out_of_lan=False, capture=False, transport=None,
          base_url='http://ai:8080', allow_http=True, model='qwen3-30b', budget=None, timeout=10,
          **changes):
    return AiClient(base_url=base_url, api_key='k' * 32, model=model,
                    capability=capability or MEASURED, policy=policy or POLICY,
                    budget=budget or dict(budget_module.DEFAULTS), out_of_lan=out_of_lan,
                    capture=capture, allow_http=allow_http, timeout=timeout,
                    transport=transport or FakeTransport(), **changes)


def sent(transport):
    """Everything the client handed to the transport, as one string."""
    return json.dumps(transport.calls)


def logged(records):
    """The log lines a call produced, rendered by the formatter that will emit them."""
    return '\n'.join(JsonLinesFormatter().format(record) for record in records)


class ConstructionTests(unittest.TestCase):
    def test_a_base_url_with_a_path_a_credential_or_plaintext_is_refused(self):
        for url in ('http://ai:8080/v1', 'https://user:pw@ai:8080', 'https://ai:8080?x=1',
                    'https://ai:8080#f', 'not-a-url', 'https://', 'http://ai:8080'):
            with self.subTest(url=url):
                with self.assertRaises(AiNotConfigured):
                    build(base_url=url, allow_http=False)
        # A project-network http:// URL is allowed only when the operator said so, as everywhere else.
        self.assertIsInstance(build(base_url='http://ai:8080', allow_http=True), AiClient)

    def test_timeout_and_model_label_are_bounded(self):
        for changes in ({'timeout': 0}, {'timeout': 21}, {'timeout': 'ten'}, {'timeout': True}):
            with self.subTest(changes=changes):
                with self.assertRaises(AiNotConfigured):
                    build(**changes)
        for label in ('', ' ', 'a b', 'a' * 161, 'a\nb', None):
            with self.subTest(label=repr(label)[:20]):
                with self.assertRaises(AiNotConfigured):
                    build(model=label)

    def test_a_client_revalidates_the_documents_it_was_given(self):
        with self.assertRaises(AiError):
            build(capability=dict(MEASURED, schema_version=7))
        with self.assertRaises(AiError):
            build(policy={'schema_version': 1, 'classes': {'public': LOCAL_ONLY}})
        with self.assertRaises(AiError):
            build(**{'budget': dict(budget_module.DEFAULTS, max_evidence_items=99)})


class GateOrderingTests(unittest.TestCase):
    """Every refusal below must reach the gate without the transport ever being touched."""

    def refused(self, transport, *, data_class='internal', evidence=None, **changes):
        """Build a client, ask for one explanation, and return the refusal plus the untouched transport.

        `slot`, `json_mode` and `streaming` belong to the request; every other keyword belongs to the
        client, so a test can say "with this budget" or "with this capability" without a second builder.
        """
        complete_keys = ('slot', 'json_mode', 'streaming')
        request = {key: changes.pop(key) for key in complete_keys if key in changes}
        with self.assertRaises(AiError) as caught:
            build(transport=transport, **changes).complete(
                instruction='why is this volume full?', data_class=data_class,
                evidence=evidence if evidence is not None else [reference()], now=NOW, **request)
        return caught.exception, transport

    def test_restricted_is_refused_and_nothing_was_sent(self):
        transport = FakeTransport()
        error, transport = self.refused(transport, data_class='restricted')
        self.assertEqual(error.code, 'policy_refused')
        self.assertEqual(transport.calls, [])

    def test_an_unclassified_bundle_is_refused_rather_than_treated_as_public(self):
        transport = FakeTransport()
        error, _transport = self.refused(transport, data_class='unknown')
        self.assertEqual(error.code, 'policy_refused')
    def test_remote_is_refused_per_class_before_any_text_exists(self):
        for name in ('internal', 'restricted'):
            transport = FakeTransport()
            error, _transport = self.refused(transport, data_class=name, out_of_lan=True)
            with self.subTest(data_class=name):
                self.assertIn(error.code, ('remote_refused', 'policy_refused'))
                self.assertEqual(transport.calls, [], 'a gate that sent the request is not a gate')

    def test_an_unmeasured_capability_blocks_the_call(self):
        transport = FakeTransport()
        error, _transport = self.refused(transport, capability=UNMEASURED)
        self.assertEqual(error.code, 'capability_unknown')
        self.assertIn('context_tokens', str(error))
        self.assertEqual(transport.calls, [])

    def test_json_mode_and_streaming_follow_the_manifest_and_the_client(self):
        transport = FakeTransport()
        error, _transport = self.refused(transport, capability=UNMEASURED, json_mode=True)
        self.assertEqual(error.code, 'capability_unknown')
        transport = FakeTransport()
        error, _transport = self.refused(transport, streaming=True)
        self.assertEqual(error.code, 'streaming_unsupported')
        self.assertEqual(transport.calls, [])

    def test_expired_evidence_refuses_without_a_second_query(self):
        transport = FakeTransport()
        error, _transport = self.refused(
            transport, evidence=[reference(expires_at='2026-09-08T10:29:00+00:00')])
        self.assertEqual(error.code, 'expired_evidence')
        self.assertEqual(transport.calls, [])

    def test_an_oversized_bundle_refuses_before_the_request_is_built(self):
        transport = FakeTransport()
        error, _transport = self.refused(
            transport, evidence=[reference() for _ in range(3)],
            budget=dict(budget_module.DEFAULTS, max_evidence_items=2))
        self.assertEqual(error.code, 'too_many_references')
        self.assertEqual(transport.calls, [])

    def test_an_empty_or_absent_instruction_is_refused(self):
        transport = FakeTransport()
        with self.assertRaises(AiError) as caught:
            build(transport=transport).complete(instruction='   ', data_class='internal',
                                                evidence=[reference()], now=NOW)
        self.assertEqual(caught.exception.code, 'invalid_instruction')
        self.assertEqual(transport.calls, [])
        with self.assertRaises(AiError) as caught:
            build(transport=transport).complete(instruction='x' * 9000, data_class='internal',
                                               evidence=[reference()], now=NOW)
        self.assertEqual(caught.exception.code, 'invalid_instruction')

    def test_an_unknown_slot_is_refused(self):
        with self.assertRaises(AiError) as caught:
            build(transport=FakeTransport()).complete(instruction='why?', data_class='internal',
                                                      evidence=[reference()], slot='clever', now=NOW)
        self.assertEqual(caught.exception.code, 'invalid_slot')


class RequestTests(unittest.TestCase):
    def test_one_call_one_attempt_and_a_honest_result(self):
        transport = FakeTransport()
        result = build(transport=transport).complete(instruction='why?', data_class='internal',
                                                     evidence=[reference()], now=NOW)
        self.assertEqual(len(transport.calls), 1)
        call = transport.calls[0]
        self.assertEqual(call['method'], 'POST')
        self.assertEqual(call['path'], '/v1/chat/completions')
        self.assertEqual(call['payload']['model'], 'qwen3-30b')
        self.assertEqual(call['payload']['stream'], False)
        self.assertEqual(call['payload']['max_tokens'], budget_module.DEFAULTS['max_completion_tokens'])
        self.assertEqual(result['status'], 'ok')
        self.assertEqual(result['content'], 'the volume filled')
        self.assertEqual(result['display_text'], 'the volume filled', 'no label on a local call')
        self.assertIsNone(result['label'])
        self.assertEqual(result['usage'], {'input_tokens': 44, 'output_tokens': 48})
        self.assertEqual(result['finish_reason'], 'stop')
        self.assertEqual(result['evidence_count'], 1)
        self.assertTrue(result['call_id'])
        self.assertNotIn('response_format', call['payload'])

    def test_the_fast_slot_is_the_one_q13_named_for_rerank_and_summarise(self):
        transport = FakeTransport(reply={'model': 'qwen3-30b-small', 'choices': [
            {'message': {'content': 'summary'}, 'finish_reason': 'stop'}]})
        result = build(transport=transport, model_fast='qwen3-30b-small').complete(
            instruction='summarise', data_class='internal', evidence=[reference()], slot='model_fast',
            now=NOW)
        self.assertEqual(transport.calls[0]['payload']['model'], 'qwen3-30b-small')
        self.assertEqual(result['slot'], 'model_fast')
        self.assertEqual(result['response_model'], 'qwen3-30b-small')

    def test_json_mode_asks_for_json_once_the_manifest_measured_it(self):
        transport = FakeTransport()
        build(transport=transport).complete(instruction='why?', data_class='internal',
                                            evidence=[reference()], json_mode=True, now=NOW)
        self.assertEqual(transport.calls[0]['payload']['response_format'], {'type': 'json_object'})

    def test_redaction_runs_on_what_leaves_the_process_not_on_what_is_returned(self):
        transport = FakeTransport()
        bundle = [reference(parameters={'rule_id': 'disk-full', 'password': CANARY,
                                       'log_line': CANARY + 'y' * 300})]
        build(transport=transport, policy={'schema_version': 1, 'classes': dict(
            POLICY['classes'], internal={'generate': True, 'remote': False,
                                         'redact': ['secret_keys', 'no_free_text'], 'label': ''})},
            ).complete(instruction='why is this volume full?', data_class='internal', evidence=bundle,
                       now=NOW)
        body = sent(transport)
        self.assertNotIn(CANARY, body)
        self.assertIn('<redacted>', body)
        self.assertIn('<withheld:free-text>', body)

    def test_a_long_instruction_is_scrubbed_for_a_class_that_names_no_free_text(self):
        transport = FakeTransport()
        prose = 'the operator wrote this sentence and it is long enough to be prose. ' + CANARY
        with self.assertLogs('local_observe.ai.telemetry', 'INFO'):
            build(transport=transport).complete(instruction=prose, data_class='public',
                                                evidence=[reference()], now=NOW)
        self.assertNotIn(CANARY, sent(transport))
        self.assertIn('<withheld:free-text>', sent(transport))

    def test_the_request_body_is_measured_after_it_is_written(self):
        transport = FakeTransport()
        limits = dict(budget_module.DEFAULTS, max_evidence_bytes=4_096, max_prompt_bytes=4_096)
        heavy = [reference(parameters={'blob': 'x' * 3_000})]
        with self.assertRaises(AiError) as caught:
            build(transport=transport, budget=limits).complete(instruction='x' * 2_000,
                                                               data_class='internal', evidence=heavy,
                                                               now=NOW)
        self.assertEqual(caught.exception.code, 'prompt_bytes')
        self.assertEqual(transport.calls, [])


class RemoteOutputTests(unittest.TestCase):
    def test_a_bundle_that_may_have_left_the_lan_is_labelled_in_the_output(self):
        transport = FakeTransport()
        result = build(transport=transport, out_of_lan=True, base_url='https://remote.example.test',
                       allow_http=False).complete(instruction='why?', data_class='public',
                                                  evidence=[reference()], now=NOW)
        self.assertTrue(result['out_of_lan'])
        self.assertEqual(result['label'], 'generated by a remote model')
        self.assertEqual(result['display_text'].splitlines()[0], 'generated by a remote model')
        self.assertEqual(result['content'], 'the volume filled', 'the text is not rewritten')

    def test_capture_is_off_unless_the_environment_says_the_exact_digit(self):
        for raw, expected in ((None, False), ('', False), ('0', False), ('1', True), ('true', False),
                              ('yes', False), (' 1 ', False), (1, False)):
            with self.subTest(raw=raw):
                self.assertEqual(telemetry_module.capture_enabled(raw), expected)

    def test_the_out_of_lan_default_is_the_restricted_one(self):
        self.assertTrue(client.endpoint_out_of_lan({}))
        self.assertTrue(client.endpoint_out_of_lan({'LO_AI_OUT_OF_LAN': 'false'}))
        self.assertTrue(client.endpoint_out_of_lan({'LO_AI_OUT_OF_LAN': ''}))
        self.assertFalse(client.endpoint_out_of_lan({'LO_AI_OUT_OF_LAN': '0'}))


class ResponseTests(unittest.TestCase):
    def test_an_oversized_response_is_refused_after_one_attempt(self):
        transport = FakeTransport(reply={'model': 'qwen3-30b', 'choices': [
            {'message': {'content': 'x' * 70_000}, 'finish_reason': 'length'}]})
        with self.assertLogs('local_observe.ai.telemetry', 'INFO'):
            with self.assertRaises(AiError) as caught:
                build(transport=transport).complete(instruction='why?', data_class='internal',
                                                    evidence=[reference()], now=NOW)
        self.assertEqual(caught.exception.code, 'response_too_large')
        self.assertEqual(len(transport.calls), 1, 'one attempt, never an ambient retry')

    def test_an_endpoint_failure_is_a_refusal_not_a_retry(self):
        transport = FakeTransport(error=TransportError('Endpoint unavailable or invalid JSON response'))
        with self.assertLogs('local_observe.ai.telemetry', 'INFO'):
            with self.assertRaises(AiError) as caught:
                build(transport=transport).complete(instruction='why?', data_class='internal',
                                                    evidence=[reference()], now=NOW)
        self.assertEqual(caught.exception.code, 'endpoint_unavailable')
        self.assertEqual(len(transport.calls), 1)

    def test_a_non_2xx_status_is_refused_and_recorded_with_its_number(self):
        transport = FakeTransport(status=503, reply=None)
        with self.assertLogs('local_observe.ai.telemetry', 'INFO') as captured:
            with self.assertRaises(AiError) as caught:
                build(transport=transport).complete(instruction='why?', data_class='internal',
                                                    evidence=[reference()], now=NOW)
        self.assertEqual(caught.exception.code, 'endpoint_status')
        self.assertEqual(len(transport.calls), 1)
        self.assertIn('"http_status": 503', logged(captured.records))

    def test_a_reply_that_is_not_an_explanation_is_refused(self):
        cases = {'malformed_response': {'model': 'qwen3-30b', 'choices': []},
                 'malformed_response 2': {'model': 'qwen3-30b'},
                 'malformed_response 3': {'choices': [{'message': 'not a mapping'}]},
                 'empty_content': {'choices': [{'message': {'content': '   '}}]}}
        for expected, reply in cases.items():
            with self.subTest(expected=expected), self.assertLogs('local_observe.ai.telemetry', 'INFO'):
                with self.assertRaises(AiError) as caught:
                    build(transport=FakeTransport(reply=reply)).complete(
                        instruction='why?', data_class='internal', evidence=[reference()], now=NOW)
                self.assertEqual(caught.exception.code, expected.split()[0])

    def test_an_endpoint_that_answers_as_another_model_is_refused(self):
        transport = FakeTransport(reply={'model': '/models/something-else.gguf', 'choices': [
            {'message': {'content': 'sure!'}, 'finish_reason': 'stop'}]})
        with self.assertLogs('local_observe.ai.telemetry', 'INFO'):
            with self.assertRaises(AiError) as caught:
                build(transport=transport).complete(instruction='why?', data_class='internal',
                                                    evidence=[reference()], now=NOW)
        self.assertEqual(caught.exception.code, 'model_mismatch')
        self.assertNotIn('sure!', sent(transport))

    def test_a_missing_usage_object_is_unknown_not_zero(self):
        transport = FakeTransport(reply={'model': 'qwen3-30b', 'choices': [
            {'message': {'content': 'ok'}, 'finish_reason': 'stop'}]})
        result = build(transport=transport).complete(instruction='why?', data_class='internal',
                                                    evidence=[reference()], now=NOW)
        self.assertEqual(result['usage'], {'input_tokens': None, 'output_tokens': None})
        self.assertEqual(client.token_count('12'), None)

    def test_missing_provider_model_is_unknown_not_the_requested_model(self):
        transport = FakeTransport(reply={'choices': [
            {'message': {'content': 'ok'}, 'finish_reason': 'stop'}]})
        result = build(transport=transport).complete(instruction='why?', data_class='internal',
                                                     evidence=[reference()], now=NOW)
        self.assertEqual(result['model'], 'qwen3-30b')
        self.assertIsNone(result['response_model'])
        self.assertEqual(client.token_count(True), None)
        self.assertEqual(client.token_count(7), 7)


class TelemetryTests(unittest.TestCase):
    def test_a_successful_call_logs_no_payload(self):
        transport = FakeTransport()
        with self.assertLogs('local_observe.ai.telemetry', 'INFO') as captured:
            build(transport=transport).complete(instruction=CANARY + ' why is this host out of disk?',
                                                data_class='internal', evidence=[reference()], now=NOW)
        line = logged(captured.records)
        self.assertNotIn(CANARY, line)
        self.assertIn('"gen_ai.operation.name": "chat"', line)
        self.assertIn('"gen_ai.request.model": "qwen3-30b"', line)
        self.assertIn('"gen_ai.usage.input_tokens": 44', line)
        self.assertIn('"capture": false', line)
        self.assertIn('"evidence_bytes"', line)
        self.assertEqual(len(captured.records), 1)

    def test_a_refusal_is_logged_as_a_warning_with_its_code_and_no_body(self):
        transport = FakeTransport()
        with self.assertLogs('local_observe.ai.telemetry', 'WARNING') as captured:
            with self.assertRaises(AiError):
                build(transport=transport).complete(instruction=CANARY, data_class='restricted',
                                                    evidence=[reference()], now=NOW)
        line = logged(captured.records)
        self.assertIn('"refusal": "policy_refused"', line)
        self.assertNotIn(CANARY, line)

    def test_capture_adds_bounded_excerpts_and_only_when_switched_on(self):
        transport = FakeTransport()
        with self.assertLogs('local_observe.ai.telemetry', 'INFO') as captured:
            build(transport=transport, capture=True).complete(instruction='z' * 400,
                                                              data_class='internal',
                                                              evidence=[reference()], now=NOW)
        line = logged(captured.records)
        self.assertIn('"capture": true', line)
        self.assertIn('capture_prompt', line)
        self.assertIn('capture_response', line)
        # The bound is the logger's own (MAX_SCALAR_LENGTH in local_observe/log.py) as well as the
        # slice in telemetry.call(), so an excerpt can never grow the log line past 300 characters.
        excerpt = line.split('"capture_prompt": "')[1].split('"')[0]
        self.assertLessEqual(len(excerpt), 300)
        self.assertTrue(excerpt.startswith('z'))


class FromEnvironmentTests(unittest.TestCase):
    def setUp(self):
        self._directory = tempfile.TemporaryDirectory()
        self.root = Path(self._directory.name)
        (self.root / 'key').write_text('k' * 48, encoding='utf-8')
        (self.root / 'capability.json').write_text(json.dumps(MEASURED), encoding='utf-8')
        (self.root / 'policy.json').write_text(json.dumps(POLICY), encoding='utf-8')
        self.environ = {'LO_AI_BASE_URL': 'http://ai:8080', 'LO_AI_API_KEY_FILE': str(self.root / 'key'),
                        'LO_AI_MODEL': 'qwen3-30b', 'LO_AI_CAPABILITY': str(self.root / 'capability.json'),
                        'LO_AI_POLICY': str(self.root / 'policy.json'), 'LO_INTERNAL_ALLOW_HTTP': '1',
                        'LO_AI_OUT_OF_LAN': '0'}

    def tearDown(self):
        self._directory.cleanup()

    def test_the_contract_is_read_from_the_environment(self):
        built = AiClient.from_environment(dict(self.environ))
        self.assertEqual(built.model, 'qwen3-30b')
        self.assertEqual(built.model_fast, 'qwen3-30b', 'the fast slot falls back to the model')
        self.assertFalse(built.out_of_lan)
        self.assertFalse(built.capture)
        environ = dict(self.environ, LO_AI_MODEL_FAST='qwen3-30b-small', LO_AI_CAPTURE='1')
        with self.assertLogs('local_observe.ai.client', 'WARNING') as captured:
            built = AiClient.from_environment(environ)
        self.assertEqual(built.model_fast, 'qwen3-30b-small')
        self.assertTrue(built.capture)
        self.assertIn('LO_AI_CAPTURE', logged(captured.records))

    def test_a_missing_variable_names_the_variable_and_says_generation_is_unavailable(self):
        for name in ('LO_AI_BASE_URL', 'LO_AI_MODEL', 'LO_AI_CAPABILITY', 'LO_AI_POLICY'):
            environ = dict(self.environ)
            del environ[name]
            with self.subTest(missing=name), self.assertRaises(AiNotConfigured) as caught:
                AiClient.from_environment(environ)
            self.assertIn(name, str(caught.exception))
            self.assertIn('not configured', str(caught.exception))
        with self.assertRaises(AiNotConfigured):
            AiClient.from_environment(dict(self.environ, LO_AI_BASE_URL='  '))

    def test_an_unset_locality_declaration_means_assume_remote(self):
        environ = dict(self.environ)
        del environ['LO_AI_OUT_OF_LAN']
        self.assertTrue(AiClient.from_environment(environ).out_of_lan)

    def test_a_credential_too_short_for_the_transport_is_refused_at_read_time(self):
        (self.root / 'short').write_text('abc', encoding='utf-8')
        with self.assertRaises(ValueError):
            AiClient.from_environment(dict(self.environ, LO_AI_API_KEY_FILE=str(self.root / 'short')))


if __name__ == '__main__':
    unittest.main()
